from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

# --- Phase 1 Models ---

class ExecutiveSummaryModel(BaseModel):
    business_overview: str = Field(..., description="Overview of the business and its value")
    current_market_position: str = Field(..., description="Analysis of current market position")
    competitive_landscape: str = Field(..., description="Summary of the competitive landscape")
    growth_opportunities: str = Field(..., description="Identified growth opportunities")
    strategic_direction: str = Field(..., description="The overall strategic direction proposed")
    business_risks: str = Field(..., description="Potential risks to this strategy")
    marketing_vision: str = Field(..., description="Long term marketing vision")
    success_definition: str = Field(..., description="How success will be defined and measured")
    expected_outcome: str = Field(..., description="The expected outcome of this strategy")
    priority_areas: List[str] = Field(..., description="Top 3-5 priority areas")
    confidence: float = Field(..., description="Confidence score for this summary (0.0 to 1.0)")
    reasoning: str = Field(..., description="Reasoning behind this summary and direction")
    source_modules: List[str] = Field(..., description="Which intelligence modules heavily influenced this")

class StrategicPillarModel(BaseModel):
    title: str = Field(..., description="Title of the strategic pillar (e.g., Founder Branding, Product Education)")
    description: str = Field(..., description="Detailed description of what this pillar covers")
    purpose: str = Field(..., description="The core purpose of this pillar in the overall strategy")
    priority: str = Field(..., description="Priority level (High, Medium, Low)")
    weight: int = Field(..., description="Percentage weight of this pillar (0-100), total across all pillars should be 100")
    recommended_content_percent: int = Field(..., description="Percentage of total content this pillar should make up")
    posting_frequency: str = Field(..., description="Suggested posting frequency for this pillar (e.g. '2x per week')")
    target_audience: str = Field(..., description="Primary audience segment this pillar targets")
    business_objective: str = Field(..., description="Which business objective this pillar serves")
    related_competitors: List[str] = Field(..., description="Competitors that influenced this pillar")
    related_trends: List[str] = Field(..., description="Market trends that influenced this pillar")
    confidence: float = Field(..., description="Confidence score for this pillar (0.0 to 1.0)")
    reasoning: str = Field(..., description="Why this pillar was selected and why it matters")

class AudienceSegmentModel(BaseModel):
    segment_name: str = Field(..., description="Name of the audience persona (e.g., Enterprise CTOs)")
    description: str = Field(..., description="Description of who this segment is")
    pain_points: List[str] = Field(..., description="Core pain points they experience")
    goals: List[str] = Field(..., description="Their primary goals and desires")
    motivations: List[str] = Field(..., description="What motivates them to take action")
    buying_stage: str = Field(..., description="Current buying stage (Awareness, Consideration, Decision)")
    decision_factors: List[str] = Field(..., description="Key factors they consider before buying")
    preferred_content: List[str] = Field(..., description="Types of content they prefer to consume")
    preferred_platforms: List[str] = Field(..., description="Platforms they frequent")
    cta_preference: str = Field(..., description="How they prefer to be called to action")
    objections: List[str] = Field(..., description="Common objections they have")
    opportunity_score: float = Field(..., description="Score out of 100 for the opportunity size of this segment")
    confidence: float = Field(..., description="Confidence score for this segment analysis (0.0 to 1.0)")
    reasoning: str = Field(..., description="Why this segment was identified and prioritized")

class MessagingFrameworkModel(BaseModel):
    core_brand_message: str = Field(..., description="The core overarching brand message")
    primary_value_proposition: str = Field(..., description="The primary value proposition")
    supporting_messages: List[str] = Field(..., description="Supporting messages and pillars")
    brand_promise: str = Field(..., description="The ultimate brand promise to the customer")
    differentiators: List[str] = Field(..., description="Key market differentiators")
    proof_points: List[str] = Field(..., description="Proof points to back up claims")
    trust_builders: List[str] = Field(..., description="Elements that build trust (e.g., Case studies, Social proof)")
    tone: str = Field(..., description="Tone of voice")
    voice: str = Field(..., description="Brand voice characteristics")
    writing_style: str = Field(..., description="Specific writing style rules")
    emotional_positioning: str = Field(..., description="The emotional state we want to leave the reader in")
    cta_framework: List[str] = Field(..., description="Frameworks for calls to action")
    objection_handling: Dict[str, str] = Field(..., description="Dictionary mapping Objections to How to Handle Them")
    messaging_hierarchy: Dict[str, Any] = Field(..., description="Structured JSON representing messaging hierarchy")
    confidence: float = Field(..., description="Confidence score for this messaging framework (0.0 to 1.0)")
    reasoning: str = Field(..., description="Why this messaging framework was chosen")

# --- Phase 2 & 3 Models ---

class PositioningStrategyModel(BaseModel):
    market_position: str = Field(...)
    unique_value_proposition: str = Field(...)
    competitive_advantage: str = Field(...)
    brand_category: str = Field(...)
    brand_perception: str = Field(...)
    differentiators: List[str] = Field(...)
    brand_personality: str = Field(...)
    pricing_position: str = Field(...)
    market_message: str = Field(...)
    customer_promise: str = Field(...)
    ideal_customer: str = Field(...)
    primary_market: str = Field(...)
    secondary_market: str = Field(...)
    blue_ocean_opportunities: List[str] = Field(...)
    positioning_risks: List[str] = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)
    source_modules: List[str] = Field(...)

class CompetitorGapModel(BaseModel):
    gap_type: str = Field(..., description="Content Gap, Keyword Gap, Messaging Gap, etc.")
    description: str = Field(...)
    impact: str = Field(..., description="High, Medium, Low")
    priority: str = Field(..., description="High, Medium, Low")
    difficulty: str = Field(..., description="High, Medium, Low")
    business_value: str = Field(...)
    suggested_solution: str = Field(...)
    competitor_reference: str = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class TrendOpportunityModel(BaseModel):
    opportunity_type: str = Field(..., description="Emerging, Growing, Seasonal, Urgent")
    title: str = Field(...)
    description: str = Field(...)
    business_impact: str = Field(...)
    urgency: str = Field(...)
    difficulty: str = Field(...)
    expected_roi: str = Field(...)
    related_industry: str = Field(...)
    related_competitors: List[str] = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class OpportunityModel(BaseModel):
    title: str = Field(...)
    opportunity_type: str = Field(...)
    opportunity_score: float = Field(...)
    business_impact: str = Field(...)
    difficulty: str = Field(...)
    estimated_timeline: str = Field(...)
    priority: str = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class StrategyRecommendationModel(BaseModel):
    title: str = Field(...)
    description: str = Field(...)
    business_impact: str = Field(...)
    priority: str = Field(...)
    expected_outcome: str = Field(...)
    estimated_effort: str = Field(...)
    related_competitors: List[str] = Field(...)
    related_trends: List[str] = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class CampaignPlanModel(BaseModel):
    campaign_name: str = Field(...)
    campaign_goal: str = Field(...)
    campaign_description: str = Field(...)
    target_audience: str = Field(...)
    business_objective: str = Field(...)
    platforms: List[str] = Field(...)
    posting_frequency: str = Field(...)
    content_mix: List[str] = Field(...)
    kpis: List[str] = Field(...)
    duration: str = Field(...)
    budget_recommendation: str = Field(...)
    priority: str = Field(...)
    success_criteria: str = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class WeeklyRoadmapModel(BaseModel):
    week_number: int = Field(..., description="1, 2, 3, or 4")
    objective: str = Field(...)
    primary_campaign: str = Field(...)
    secondary_campaign: str = Field(...)
    target_audience: str = Field(...)
    content_mix: List[str] = Field(...)
    strategic_focus: str = Field(...)
    expected_kpi: str = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class MonthlyRoadmapModel(BaseModel):
    month_number: int = Field(...)
    executive_goal: str = Field(...)
    monthly_objectives: List[str] = Field(...)
    campaign_timeline: Dict[str, Any] = Field(...)
    major_themes: List[str] = Field(...)
    posting_distribution: Dict[str, Any] = Field(...)
    expected_outcomes: List[str] = Field(...)
    risks: List[str] = Field(...)
    kpis: List[str] = Field(...)
    review_points: List[str] = Field(...)
    optimization_opportunities: List[str] = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class RiskAssessmentModel(BaseModel):
    risk_type: str = Field(...)
    description: str = Field(...)
    priority: str = Field(...)
    mitigation_strategy: str = Field(...)
    likelihood: str = Field(...)
    business_impact: str = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class StrategyMetricModel(BaseModel):
    metric_name: str = Field(...)
    target: str = Field(...)
    expected_improvement: str = Field(...)
    confidence: float = Field(...)
    reasoning: str = Field(...)

class ConfidenceBreakdownModel(BaseModel):
    overall_confidence: float = Field(...)
    business_confidence: float = Field(...)
    brand_confidence: float = Field(...)
    competitor_confidence: float = Field(...)
    trend_confidence: float = Field(...)
    recommendation_confidence: float = Field(...)
    campaign_confidence: float = Field(...)
    business_reasoning: str = Field(...)
    brand_reasoning: str = Field(...)
    competitor_reasoning: str = Field(...)
    trend_reasoning: str = Field(...)

# --- MASTER STRATEGY ---

class MasterStrategyPart1(BaseModel):
    # Phase 1 + Positioning + Gaps
    executive_summary: ExecutiveSummaryModel = Field(...)
    strategic_pillars: List[StrategicPillarModel] = Field(...)
    audience_segments: List[AudienceSegmentModel] = Field(...)
    messaging_framework: MessagingFrameworkModel = Field(...)
    positioning: PositioningStrategyModel = Field(...)
    competitor_gaps: List[CompetitorGapModel] = Field(...)
    trend_opportunities: List[TrendOpportunityModel] = Field(...)

class MasterStrategyPart2(BaseModel):
    # Phase 3
    opportunities: List[OpportunityModel] = Field(...)
    recommendations: List[StrategyRecommendationModel] = Field(...)
    campaigns: List[CampaignPlanModel] = Field(...)
    weekly_roadmaps: List[WeeklyRoadmapModel] = Field(...)
    monthly_roadmaps: List[MonthlyRoadmapModel] = Field(...)
    risks: List[RiskAssessmentModel] = Field(...)
    metrics: List[StrategyMetricModel] = Field(...)
    confidence_breakdown: ConfidenceBreakdownModel = Field(...)

class MasterStrategyResponse(BaseModel):
    # Phase 1
    executive_summary: ExecutiveSummaryModel = Field(...)
    strategic_pillars: List[StrategicPillarModel] = Field(...)
    audience_segments: List[AudienceSegmentModel] = Field(...)
    messaging_framework: MessagingFrameworkModel = Field(...)
    # Phase 2 & 3
    positioning: PositioningStrategyModel = Field(...)
    competitor_gaps: List[CompetitorGapModel] = Field(...)
    trend_opportunities: List[TrendOpportunityModel] = Field(...)
    opportunities: List[OpportunityModel] = Field(...)
    recommendations: List[StrategyRecommendationModel] = Field(...)
    campaigns: List[CampaignPlanModel] = Field(...)
    weekly_roadmaps: List[WeeklyRoadmapModel] = Field(...)
    monthly_roadmaps: List[MonthlyRoadmapModel] = Field(...)
    risks: List[RiskAssessmentModel] = Field(...)
    metrics: List[StrategyMetricModel] = Field(...)
    confidence_breakdown: ConfidenceBreakdownModel = Field(...)
