"""Add system models for RC-1

Revision ID: 176655fd0175
Revises: 2b21ebe36ce5
Create Date: 2026-08-05 19:00:21.558841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176655fd0175'
down_revision = '2b21ebe36ce5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_locks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('system_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('workflow_run_id', sa.Integer(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_audit_logs_business_id'), 'system_audit_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_created_at'), 'system_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_event_type'), 'system_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_id'), 'system_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_workflow_run_id'), 'system_audit_logs', ['workflow_run_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('developer_mode_enabled', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'developer_mode_enabled')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_system_audit_logs_workflow_run_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_event_type'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_created_at'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_business_id'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('system_locks')
    # ### end Alembic commands ###
