"""Add Phase 3 publishing features

Revision ID: 298f9df68a9c
Revises: 689cadb0702a
Create Date: 2026-07-27 13:39:49.213986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '298f9df68a9c'
down_revision = '689cadb0702a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('platform_accounts', sa.Column('token_expiry', sa.DateTime(), nullable=True))
    op.add_column('platform_accounts', sa.Column('permissions', sa.Text(), nullable=True))
    op.add_column('publishing_jobs', sa.Column('verified_published_at', sa.DateTime(), nullable=True))
    op.add_column('publishing_jobs', sa.Column('platform_post_id', sa.String(), nullable=True))
    op.add_column('publishing_jobs', sa.Column('published_url', sa.String(), nullable=True))
    op.add_column('publishing_jobs', sa.Column('api_response', sa.Text(), nullable=True))
    op.add_column('publishing_jobs', sa.Column('request_duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishing_jobs', 'request_duration_ms')
    op.drop_column('publishing_jobs', 'api_response')
    op.drop_column('publishing_jobs', 'published_url')
    op.drop_column('publishing_jobs', 'platform_post_id')
    op.drop_column('publishing_jobs', 'verified_published_at')
    op.drop_column('platform_accounts', 'permissions')
    op.drop_column('platform_accounts', 'token_expiry')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
