"""add_autonomous_workflow_orchestrator

Adds the persistent state-machine tables for the autonomous AI Growth
Operating System orchestrator (WorkflowRun, ContentPipelineRun,
WorkflowSchedule) and the Visual Intelligence Agent's image columns on
PlatformVariation.

Also brings alembic/env.py's model import list up to date with
models.workflow / models.orchestration / models.workflow_run /
models.workflow_schedule (models.analytics, models.performance_intelligence,
and models.recommendation are pure Pydantic, not SQLAlchemy, so they don't
add anything to this diff) - this is what surfaces the pre-existing
apscheduler_jobs drop below.

`apscheduler_jobs` is intentionally NOT dropped here even though autogenerate
flagged it as "removed": it's a table APScheduler's SQLAlchemyJobStore
creates and manages itself at runtime (see publishing/scheduler/core.py), not
one of our SQLAlchemy models, so it will never appear in target_metadata.

Revision ID: 2b21ebe36ce5
Revises: 26e5b9b173e1
Create Date: 2026-08-05 18:16:53.179887

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2b21ebe36ce5'
down_revision = '26e5b9b173e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('cadence_days', sa.Integer(), nullable=False),
    sa.Column('preferred_day_of_week', sa.String(length=20), nullable=False),
    sa.Column('preferred_time', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_schedules_business_id'), 'workflow_schedules', ['business_id'], unique=True)
    op.create_index(op.f('ix_workflow_schedules_id'), 'workflow_schedules', ['id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('cycle_stage', sa.Enum('BUSINESS_READY', 'CONTENT_INTELLIGENCE_RUNNING', 'CONTENT_INTELLIGENCE_COMPLETED', 'BRAND_INTELLIGENCE_RUNNING', 'BRAND_INTELLIGENCE_COMPLETED', 'MARKET_INTELLIGENCE_RUNNING', 'MARKET_INTELLIGENCE_COMPLETED', 'COMPETITOR_INTELLIGENCE_RUNNING', 'COMPETITOR_INTELLIGENCE_COMPLETED', 'STRATEGY_GENERATING', 'STRATEGY_READY', 'WEEKLY_PLAN_GENERATING', 'WEEKLY_PLAN_READY', 'COMPLETED', 'FAILED', name='cyclestage'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', name='runstatus'), nullable=False),
    sa.Column('weekly_plan_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['execution_weekly_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_business_id'), 'workflow_runs', ['business_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    op.create_table('content_pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('content_slot_id', sa.Integer(), nullable=False),
    sa.Column('generated_content_id', sa.Integer(), nullable=True),
    sa.Column('variation_id', sa.Integer(), nullable=True),
    sa.Column('publishing_job_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('CONTENT_GENERATING', 'CONTENT_READY', 'IMAGE_SELECTING', 'IMAGE_READY', 'QUALITY_REVIEW', 'PENDING_APPROVAL', 'CHANGES_REQUESTED', 'APPROVED', 'QUEUED', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'ANALYTICS_RUNNING', 'LEARNING_RUNNING', 'COMPLETED', 'FAILED', name='contentpipelinestage'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', name='runstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_slot_id'], ['execution_content_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_content_id'], ['content_generated.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publishing_job_id'], ['publishing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variation_id'], ['content_platform_variations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pipeline_runs_id'), 'content_pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_content_pipeline_runs_workflow_run_id'), 'content_pipeline_runs', ['workflow_run_id'], unique=False)
    # NOTE: apscheduler_jobs is intentionally left alone - see module docstring.
    op.add_column('content_platform_variations', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('content_platform_variations', sa.Column('image_thumbnail_url', sa.String(length=1000), nullable=True))
    op.add_column('content_platform_variations', sa.Column('image_source', sa.String(length=50), nullable=True))
    op.add_column('content_platform_variations', sa.Column('image_external_id', sa.String(length=100), nullable=True))
    op.add_column('content_platform_variations', sa.Column('image_attribution', sa.String(length=255), nullable=True))
    op.add_column('content_platform_variations', sa.Column('image_selection_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_platform_variations', 'image_selection_reasoning')
    op.drop_column('content_platform_variations', 'image_attribution')
    op.drop_column('content_platform_variations', 'image_external_id')
    op.drop_column('content_platform_variations', 'image_source')
    op.drop_column('content_platform_variations', 'image_thumbnail_url')
    op.drop_column('content_platform_variations', 'image_url')
    # NOTE: apscheduler_jobs is intentionally left alone - see module docstring.
    op.drop_index(op.f('ix_content_pipeline_runs_workflow_run_id'), table_name='content_pipeline_runs')
    op.drop_index(op.f('ix_content_pipeline_runs_id'), table_name='content_pipeline_runs')
    op.drop_table('content_pipeline_runs')
    op.drop_index(op.f('ix_workflow_runs_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_business_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_workflow_schedules_id'), table_name='workflow_schedules')
    op.drop_index(op.f('ix_workflow_schedules_business_id'), table_name='workflow_schedules')
    op.drop_table('workflow_schedules')
    # ### end Alembic commands ###
