"""Add content chunks and processing fields

Revision ID: 34db510f558c
Revises: 61ffc589114d
Create Date: 2026-07-22 14:00:35.377870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34db510f558c'
down_revision = '61ffc589114d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_content_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_title', sa.String(), nullable=True),
    sa.Column('text_content', sa.String(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imported_content_id'], ['imported_contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_chunks_id'), 'content_chunks', ['id'], unique=False)
    op.add_column('imported_contents', sa.Column('extracted_text', sa.String(), nullable=True))
    op.add_column('imported_contents', sa.Column('cleaned_text', sa.String(), nullable=True))
    op.add_column('imported_contents', sa.Column('language', sa.String(), nullable=True))
    op.add_column('imported_contents', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('imported_contents', sa.Column('sentence_count', sa.Integer(), nullable=True))
    op.add_column('imported_contents', sa.Column('paragraph_count', sa.Integer(), nullable=True))
    op.add_column('imported_contents', sa.Column('estimated_read_time', sa.Integer(), nullable=True))
    op.add_column('imported_contents', sa.Column('content_hash', sa.String(), nullable=True))
    processing_status_enum = sa.Enum('PENDING', 'EXTRACTING', 'CLEANING', 'CHUNKING', 'COMPLETED', 'FAILED', name='processingstatus')
    processing_status_enum.create(op.get_bind())
    op.add_column('imported_contents', sa.Column('processing_status', processing_status_enum, nullable=False, server_default='PENDING'))
    op.add_column('imported_contents', sa.Column('processing_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imported_contents', 'processing_error')
    op.drop_column('imported_contents', 'processing_status')
    op.drop_column('imported_contents', 'content_hash')
    op.drop_column('imported_contents', 'estimated_read_time')
    op.drop_column('imported_contents', 'paragraph_count')
    op.drop_column('imported_contents', 'sentence_count')
    op.drop_column('imported_contents', 'word_count')
    op.drop_column('imported_contents', 'language')
    op.drop_column('imported_contents', 'cleaned_text')
    op.drop_column('imported_contents', 'extracted_text')
    op.drop_index(op.f('ix_content_chunks_id'), table_name='content_chunks')
    op.drop_table('content_chunks')
    # ### end Alembic commands ###
