"""Add content import tables

Revision ID: 61ffc589114d
Revises: b8d1068645e6
Create Date: 2026-07-22 13:24:51.194697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ffc589114d'
down_revision = 'b8d1068645e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'UPLOADED', 'VALIDATING', 'READY', 'IMPORTED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_imports_id'), 'content_imports', ['id'], unique=False)
    op.create_index(op.f('ix_content_imports_user_id'), 'content_imports', ['user_id'], unique=False)
    op.create_table('imported_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['content_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_contents_id'), 'imported_contents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imported_contents_id'), table_name='imported_contents')
    op.drop_table('imported_contents')
    op.drop_index(op.f('ix_content_imports_user_id'), table_name='content_imports')
    op.drop_index(op.f('ix_content_imports_id'), table_name='content_imports')
    op.drop_table('content_imports')
    # ### end Alembic commands ###
