"""Add Phase 2 publishing features

Revision ID: 689cadb0702a
Revises: d2651dd878dc
Create Date: 2026-07-27 13:25:29.369222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689cadb0702a'
down_revision = 'd2651dd878dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing_automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_automation_rules_id'), 'publishing_automation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_publishing_automation_rules_platform_name'), 'publishing_automation_rules', ['platform_name'], unique=False)
    op.create_table('publishing_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['publishing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_notifications_id'), 'publishing_notifications', ['id'], unique=False)
    op.add_column('publishing_jobs', sa.Column('readiness_score', sa.Integer(), nullable=True))
    op.add_column('publishing_jobs', sa.Column('validation_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishing_jobs', 'validation_report')
    op.drop_column('publishing_jobs', 'readiness_score')
    op.drop_index(op.f('ix_publishing_notifications_id'), table_name='publishing_notifications')
    op.drop_table('publishing_notifications')
    op.drop_index(op.f('ix_publishing_automation_rules_platform_name'), table_name='publishing_automation_rules')
    op.drop_index(op.f('ix_publishing_automation_rules_id'), table_name='publishing_automation_rules')
    op.drop_table('publishing_automation_rules')
    # ### end Alembic commands ###
