"""Add Brand Intelligence models

Revision ID: 7c189d9a8dd9
Revises: b652ae0e541b
Create Date: 2026-07-23 16:13:15.142060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c189d9a8dd9'
down_revision = 'b652ae0e541b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('core_mission', sa.Text(), nullable=True),
    sa.Column('primary_industry', sa.String(length=255), nullable=True),
    sa.Column('primary_expertise', sa.String(length=255), nullable=True),
    sa.Column('primary_services', sa.JSON(), nullable=True),
    sa.Column('unique_selling_points', sa.JSON(), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('communication_objectives', sa.JSON(), nullable=True),
    sa.Column('brand_vision', sa.Text(), nullable=True),
    sa.Column('brand_positioning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index(op.f('ix_brand_profiles_id'), 'brand_profiles', ['id'], unique=False)
    op.create_table('brand_confidence_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('current_confidence', sa.Float(), nullable=False),
    sa.Column('previous_confidence', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('knowledge_coverage', sa.Float(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_confidence_scores_id'), 'brand_confidence_scores', ['id'], unique=False)
    op.create_table('brand_content_pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('pillar_name', sa.String(length=255), nullable=False),
    sa.Column('pillar_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_content_pillars_id'), 'brand_content_pillars', ['id'], unique=False)
    op.create_table('brand_cta_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('cta_text', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_cta_patterns_id'), 'brand_cta_patterns', ['id'], unique=False)
    op.create_table('brand_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('keyword_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_keywords_id'), 'brand_keywords', ['id'], unique=False)
    op.create_table('brand_memory_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('generation_duration', sa.Integer(), nullable=True),
    sa.Column('overall_confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_memory_versions_id'), 'brand_memory_versions', ['id'], unique=False)
    op.create_table('brand_personality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('trait', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_personality_id'), 'brand_personality', ['id'], unique=False)
    op.create_table('brand_posting_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('avg_sentence_length', sa.Float(), nullable=True),
    sa.Column('paragraph_structure', sa.String(length=255), nullable=True),
    sa.Column('vocabulary_complexity', sa.String(length=100), nullable=True),
    sa.Column('storytelling_preference', sa.String(length=100), nullable=True),
    sa.Column('educational_vs_promotional_ratio', sa.String(length=100), nullable=True),
    sa.Column('technical_depth', sa.String(length=100), nullable=True),
    sa.Column('reading_difficulty', sa.String(length=100), nullable=True),
    sa.Column('content_strategy', sa.JSON(), nullable=True),
    sa.Column('strategy_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_posting_patterns_id'), 'brand_posting_patterns', ['id'], unique=False)
    op.create_table('brand_storytelling_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_storytelling_patterns_id'), 'brand_storytelling_patterns', ['id'], unique=False)
    op.create_table('brand_target_audiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('audience_segment', sa.String(length=255), nullable=False),
    sa.Column('audience_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_target_audiences_id'), 'brand_target_audiences', ['id'], unique=False)
    op.create_table('brand_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('topic_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_topics_id'), 'brand_topics', ['id'], unique=False)
    op.create_table('brand_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('word_or_phrase', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_vocabulary_id'), 'brand_vocabulary', ['id'], unique=False)
    op.create_table('brand_voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('characteristic', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_voice_id'), 'brand_voice', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_voice_id'), table_name='brand_voice')
    op.drop_table('brand_voice')
    op.drop_index(op.f('ix_brand_vocabulary_id'), table_name='brand_vocabulary')
    op.drop_table('brand_vocabulary')
    op.drop_index(op.f('ix_brand_topics_id'), table_name='brand_topics')
    op.drop_table('brand_topics')
    op.drop_index(op.f('ix_brand_target_audiences_id'), table_name='brand_target_audiences')
    op.drop_table('brand_target_audiences')
    op.drop_index(op.f('ix_brand_storytelling_patterns_id'), table_name='brand_storytelling_patterns')
    op.drop_table('brand_storytelling_patterns')
    op.drop_index(op.f('ix_brand_posting_patterns_id'), table_name='brand_posting_patterns')
    op.drop_table('brand_posting_patterns')
    op.drop_index(op.f('ix_brand_personality_id'), table_name='brand_personality')
    op.drop_table('brand_personality')
    op.drop_index(op.f('ix_brand_memory_versions_id'), table_name='brand_memory_versions')
    op.drop_table('brand_memory_versions')
    op.drop_index(op.f('ix_brand_keywords_id'), table_name='brand_keywords')
    op.drop_table('brand_keywords')
    op.drop_index(op.f('ix_brand_cta_patterns_id'), table_name='brand_cta_patterns')
    op.drop_table('brand_cta_patterns')
    op.drop_index(op.f('ix_brand_content_pillars_id'), table_name='brand_content_pillars')
    op.drop_table('brand_content_pillars')
    op.drop_index(op.f('ix_brand_confidence_scores_id'), table_name='brand_confidence_scores')
    op.drop_table('brand_confidence_scores')
    op.drop_index(op.f('ix_brand_profiles_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
