"""Add Phase 5 Analysis Models

Revision ID: b652ae0e541b
Revises: 34db510f558c
Create Date: 2026-07-22 14:25:25.437749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b652ae0e541b'
down_revision = '34db510f558c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_content_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('analysis_version', sa.String(length=50), nullable=True),
    sa.Column('raw_prompt', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imported_content_id'], ['imported_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    op.create_table('document_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_content_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imported_content_id'], ['imported_contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imported_content_id')
    )
    op.create_index(op.f('ix_document_analysis_id'), 'document_analysis', ['id'], unique=False)
    op.create_table('analysis_audience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('audience_segment', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_audience_id'), 'analysis_audience', ['id'], unique=False)
    op.create_table('analysis_ctas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('cta_text', sa.Text(), nullable=False),
    sa.Column('cta_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_ctas_id'), 'analysis_ctas', ['id'], unique=False)
    op.create_table('analysis_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('keyword_type', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_keywords_id'), 'analysis_keywords', ['id'], unique=False)
    op.create_table('analysis_pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('pillar_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_pillars_id'), 'analysis_pillars', ['id'], unique=False)
    op.create_table('analysis_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('style_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_styles_id'), 'analysis_styles', ['id'], unique=False)
    op.create_table('analysis_tones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('tone_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tones_id'), 'analysis_tones', ['id'], unique=False)
    op.create_table('analysis_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('topic_type', sa.String(length=50), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_topics_id'), 'analysis_topics', ['id'], unique=False)
    from sqlalchemy.dialects import postgresql
    analysis_status_enum = postgresql.ENUM('PENDING', 'READY_FOR_AI', 'QUEUED_FOR_ANALYSIS', 'ANALYZING', 'ANALYZED', 'FAILED', name='analysis_status_enum', create_type=False)
    analysis_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('imported_contents', sa.Column('analysis_status', sa.Enum('PENDING', 'READY_FOR_AI', 'QUEUED_FOR_ANALYSIS', 'ANALYZING', 'ANALYZED', 'FAILED', name='analysis_status_enum'), nullable=True))
    op.add_column('imported_contents', sa.Column('analyzed_at', sa.DateTime(), nullable=True))
    op.alter_column('imported_contents', 'processing_error',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imported_contents', 'processing_error',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('imported_contents', 'analyzed_at')
    op.drop_column('imported_contents', 'analysis_status')
    op.execute('DROP TYPE analysis_status_enum')
    op.drop_index(op.f('ix_analysis_topics_id'), table_name='analysis_topics')
    op.drop_table('analysis_topics')
    op.drop_index(op.f('ix_analysis_tones_id'), table_name='analysis_tones')
    op.drop_table('analysis_tones')
    op.drop_index(op.f('ix_analysis_styles_id'), table_name='analysis_styles')
    op.drop_table('analysis_styles')
    op.drop_index(op.f('ix_analysis_pillars_id'), table_name='analysis_pillars')
    op.drop_table('analysis_pillars')
    op.drop_index(op.f('ix_analysis_keywords_id'), table_name='analysis_keywords')
    op.drop_table('analysis_keywords')
    op.drop_index(op.f('ix_analysis_ctas_id'), table_name='analysis_ctas')
    op.drop_table('analysis_ctas')
    op.drop_index(op.f('ix_analysis_audience_id'), table_name='analysis_audience')
    op.drop_table('analysis_audience')
    op.drop_index(op.f('ix_document_analysis_id'), table_name='document_analysis')
    op.drop_table('document_analysis')
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
