"""initial

Revision ID: b8d1068645e6
Revises: 
Create Date: 2026-07-22 08:46:06.605327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d1068645e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('usp', sa.Text(), nullable=True),
    sa.Column('primary_audience', sa.String(), nullable=True),
    sa.Column('secondary_audience', sa.String(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('customer_goals', sa.JSON(), nullable=True),
    sa.Column('marketing_goals', sa.JSON(), nullable=True),
    sa.Column('lead_generation_goals', sa.JSON(), nullable=True),
    sa.Column('brand_objectives', sa.Text(), nullable=True),
    sa.Column('content_objectives', sa.Text(), nullable=True),
    sa.Column('brand_voice', sa.String(), nullable=False),
    sa.Column('writing_style', sa.String(), nullable=True),
    sa.Column('cta_style', sa.String(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_company_name'), 'business_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_business_profiles_industry'), 'business_profiles', ['industry'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_profiles_industry'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_company_name'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
