"""Add publishing models

Revision ID: d2651dd878dc
Revises: f6d7bdfa332c
Create Date: 2026-07-27 13:17:33.352489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2651dd878dc'
down_revision = 'f6d7bdfa332c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_accounts_id'), 'platform_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_platform_accounts_platform_name'), 'platform_accounts', ['platform_name'], unique=False)
    op.create_table('publishing_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['content_platform_variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_approvals_id'), 'publishing_approvals', ['id'], unique=False)
    op.create_table('publishing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'APPROVED', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'ARCHIVED', name='publishingstatus'), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['content_platform_variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_jobs_id'), 'publishing_jobs', ['id'], unique=False)
    op.create_table('publishing_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['publishing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_errors_id'), 'publishing_errors', ['id'], unique=False)
    op.create_table('publishing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['publishing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_history_id'), 'publishing_history', ['id'], unique=False)
    op.create_table('publishing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['publishing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_logs_id'), 'publishing_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_logs_id'), table_name='publishing_logs')
    op.drop_table('publishing_logs')
    op.drop_index(op.f('ix_publishing_history_id'), table_name='publishing_history')
    op.drop_table('publishing_history')
    op.drop_index(op.f('ix_publishing_errors_id'), table_name='publishing_errors')
    op.drop_table('publishing_errors')
    op.drop_index(op.f('ix_publishing_jobs_id'), table_name='publishing_jobs')
    op.drop_table('publishing_jobs')
    op.drop_index(op.f('ix_publishing_approvals_id'), table_name='publishing_approvals')
    op.drop_table('publishing_approvals')
    op.drop_index(op.f('ix_platform_accounts_platform_name'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_accounts_id'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    # ### end Alembic commands ###
