"""Add market intelligence models

Revision ID: e52fe00d73dc
Revises: 7c189d9a8dd9
Create Date: 2026-07-23 17:30:30.092994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52fe00d73dc'
down_revision = '7c189d9a8dd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_raw_articles_id'), 'raw_articles', ['id'], unique=False)
    op.create_table('raw_competitor_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_raw_competitor_pages_id'), 'raw_competitor_pages', ['id'], unique=False)
    op.create_table('raw_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_raw_news_id'), 'raw_news', ['id'], unique=False)
    op.create_table('raw_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_raw_posts_id'), 'raw_posts', ['id'], unique=False)
    op.create_table('raw_social_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_raw_social_content_id'), 'raw_social_content', ['id'], unique=False)
    op.create_table('trend_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.Column('url_or_query', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_sources_id'), 'trend_sources', ['id'], unique=False)
    op.create_table('trend_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_name')
    )
    op.create_index(op.f('ix_trend_topics_id'), 'trend_topics', ['id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('youtube_url', sa.String(length=255), nullable=True),
    sa.Column('blog_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_ai_suggested', sa.Integer(), nullable=True),
    sa.Column('suggestion_confidence', sa.Float(), nullable=True),
    sa.Column('suggestion_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)
    op.create_table('market_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('market_overview', sa.Text(), nullable=True),
    sa.Column('competitor_landscape', sa.Text(), nullable=True),
    sa.Column('emerging_trends', sa.Text(), nullable=True),
    sa.Column('content_opportunities', sa.JSON(), nullable=True),
    sa.Column('audience_opportunities', sa.JSON(), nullable=True),
    sa.Column('keyword_opportunities', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('threats', sa.JSON(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_insights_id'), 'market_insights', ['id'], unique=False)
    op.create_table('trend_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_topic_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trend_topic_id'], ['trend_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_articles_id'), 'trend_articles', ['id'], unique=False)
    op.create_table('trend_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_topic_id', sa.Integer(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('audience_impact', sa.Text(), nullable=True),
    sa.Column('marketing_opportunity', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trend_topic_id'], ['trend_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_insights_id'), 'trend_insights', ['id'], unique=False)
    op.create_table('trend_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_topic_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trend_topic_id'], ['trend_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_keywords_id'), 'trend_keywords', ['id'], unique=False)
    op.create_table('trend_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_topic_id', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('recency', sa.Float(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('business_fit', sa.Float(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trend_topic_id'], ['trend_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_scores_id'), 'trend_scores', ['id'], unique=False)
    op.create_table('competitor_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('content_gap', sa.Text(), nullable=True),
    sa.Column('keyword_gap', sa.Text(), nullable=True),
    sa.Column('audience_gap', sa.Text(), nullable=True),
    sa.Column('topic_gap', sa.Text(), nullable=True),
    sa.Column('platform_gap', sa.Text(), nullable=True),
    sa.Column('positioning_gap', sa.Text(), nullable=True),
    sa.Column('messaging_gap', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_analysis_id'), 'competitor_analysis', ['id'], unique=False)
    op.create_table('competitor_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('is_seo_target', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_keywords_id'), 'competitor_keywords', ['id'], unique=False)
    op.create_table('competitor_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('cta', sa.String(length=255), nullable=True),
    sa.Column('storytelling_pattern', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_posts_id'), 'competitor_posts', ['id'], unique=False)
    op.create_table('competitor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('audience', sa.JSON(), nullable=True),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('usp', sa.Text(), nullable=True),
    sa.Column('brand_voice', sa.String(length=255), nullable=True),
    sa.Column('content_style', sa.String(length=255), nullable=True),
    sa.Column('posting_frequency', sa.String(length=100), nullable=True),
    sa.Column('marketing_channels', sa.JSON(), nullable=True),
    sa.Column('content_formats', sa.JSON(), nullable=True),
    sa.Column('growth_strategy', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_profiles_id'), 'competitor_profiles', ['id'], unique=False)
    op.create_table('competitor_swot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('threats', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_swot_id'), 'competitor_swot', ['id'], unique=False)
    op.create_table('competitor_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_topics_id'), 'competitor_topics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_topics_id'), table_name='competitor_topics')
    op.drop_table('competitor_topics')
    op.drop_index(op.f('ix_competitor_swot_id'), table_name='competitor_swot')
    op.drop_table('competitor_swot')
    op.drop_index(op.f('ix_competitor_profiles_id'), table_name='competitor_profiles')
    op.drop_table('competitor_profiles')
    op.drop_index(op.f('ix_competitor_posts_id'), table_name='competitor_posts')
    op.drop_table('competitor_posts')
    op.drop_index(op.f('ix_competitor_keywords_id'), table_name='competitor_keywords')
    op.drop_table('competitor_keywords')
    op.drop_index(op.f('ix_competitor_analysis_id'), table_name='competitor_analysis')
    op.drop_table('competitor_analysis')
    op.drop_index(op.f('ix_trend_scores_id'), table_name='trend_scores')
    op.drop_table('trend_scores')
    op.drop_index(op.f('ix_trend_keywords_id'), table_name='trend_keywords')
    op.drop_table('trend_keywords')
    op.drop_index(op.f('ix_trend_insights_id'), table_name='trend_insights')
    op.drop_table('trend_insights')
    op.drop_index(op.f('ix_trend_articles_id'), table_name='trend_articles')
    op.drop_table('trend_articles')
    op.drop_index(op.f('ix_market_insights_id'), table_name='market_insights')
    op.drop_table('market_insights')
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_trend_topics_id'), table_name='trend_topics')
    op.drop_table('trend_topics')
    op.drop_index(op.f('ix_trend_sources_id'), table_name='trend_sources')
    op.drop_table('trend_sources')
    op.drop_index(op.f('ix_raw_social_content_id'), table_name='raw_social_content')
    op.drop_table('raw_social_content')
    op.drop_index(op.f('ix_raw_posts_id'), table_name='raw_posts')
    op.drop_table('raw_posts')
    op.drop_index(op.f('ix_raw_news_id'), table_name='raw_news')
    op.drop_table('raw_news')
    op.drop_index(op.f('ix_raw_competitor_pages_id'), table_name='raw_competitor_pages')
    op.drop_table('raw_competitor_pages')
    op.drop_index(op.f('ix_raw_articles_id'), table_name='raw_articles')
    op.drop_table('raw_articles')
    # ### end Alembic commands ###
