"""Add publishing fields to GeneratedContent

Revision ID: e6ec98bcbdfe
Revises: 4ed56e60e66b
Create Date: 2026-07-28 14:35:24.016479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6ec98bcbdfe'
down_revision = '4ed56e60e66b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_generated', sa.Column('publish_status', sa.String(length=50), nullable=True))
    op.add_column('content_generated', sa.Column('publish_mode', sa.String(length=50), nullable=True))
    op.add_column('content_generated', sa.Column('target_platforms', sa.JSON(), nullable=True))
    op.add_column('content_generated', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('content_generated', sa.Column('publishing_job_id', sa.Integer(), nullable=True))
    op.add_column('content_generated', sa.Column('approved_by', sa.String(length=255), nullable=True))
    op.add_column('content_generated', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('content_generated', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('content_generated', sa.Column('platform_post_id', sa.String(length=255), nullable=True))
    op.add_column('content_generated', sa.Column('published_url', sa.String(length=500), nullable=True))
    op.add_column('content_generated', sa.Column('publishing_error', sa.Text(), nullable=True))
    op.add_column('content_generated', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'content_generated', 'publishing_jobs', ['publishing_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_generated', type_='foreignkey')
    op.drop_column('content_generated', 'verification_status')
    op.drop_column('content_generated', 'publishing_error')
    op.drop_column('content_generated', 'published_url')
    op.drop_column('content_generated', 'platform_post_id')
    op.drop_column('content_generated', 'published_at')
    op.drop_column('content_generated', 'approved_at')
    op.drop_column('content_generated', 'approved_by')
    op.drop_column('content_generated', 'publishing_job_id')
    op.drop_column('content_generated', 'scheduled_at')
    op.drop_column('content_generated', 'target_platforms')
    op.drop_column('content_generated', 'publish_mode')
    op.drop_column('content_generated', 'publish_status')
    # ### end Alembic commands ###
