"""add_user_id_to_business_profile

Revision ID: e77f41adfa6b
Revises: 176655fd0175
Create Date: 2026-08-05 19:35:53.164915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77f41adfa6b'
down_revision = '176655fd0175'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'business_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_profiles', type_='foreignkey')
    op.drop_column('business_profiles', 'user_id')
    # ### end Alembic commands ###
