"""expand publishing status enum, add approval token and audit log tables

Revision ID: f57f0df8a84d
Revises: e6ec98bcbdfe
Create Date: 2026-08-05 00:00:04.472635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f57f0df8a84d'
down_revision = 'e6ec98bcbdfe'
branch_labels = None
depends_on = None


NEW_STATUS_VALUES = ['AI_REVIEW', 'PENDING_APPROVAL', 'QUEUED', 'ANALYZING', 'COMPLETED', 'CANCELLED']


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for value in NEW_STATUS_VALUES:
        op.execute(f"ALTER TYPE publishingstatus ADD VALUE IF NOT EXISTS '{value}'")

    op.create_table('publishing_approval_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['publishing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_approval_tokens_id'), 'publishing_approval_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_publishing_approval_tokens_token'), 'publishing_approval_tokens', ['token'], unique=True)
    op.create_table('publishing_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('approval_token_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_token_id'], ['publishing_approval_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['publishing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_audit_logs_id'), 'publishing_audit_logs', ['id'], unique=False)
    # NOTE: autogenerate also proposed dropping 'apscheduler_jobs' and 'agent_task_statuses'.
    # Those tables are unrelated to this change (they're just not imported into
    # migrations/env.py's model list), so those drops were intentionally left out
    # to avoid destroying live scheduler/agent-status data.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_audit_logs_id'), table_name='publishing_audit_logs')
    op.drop_table('publishing_audit_logs')
    op.drop_index(op.f('ix_publishing_approval_tokens_token'), table_name='publishing_approval_tokens')
    op.drop_index(op.f('ix_publishing_approval_tokens_id'), table_name='publishing_approval_tokens')
    op.drop_table('publishing_approval_tokens')
    # ### end Alembic commands ###
    # NOTE: newly added enum values are intentionally not removed on downgrade -
    # Postgres does not support removing individual enum values without
    # recreating the type, and any rows already using the new statuses would break.
