"""Add Multi-Platform models

Revision ID: f6d7bdfa332c
Revises: e52fe00d73dc
Create Date: 2026-07-27 13:01:02.308550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d7bdfa332c'
down_revision = 'e52fe00d73dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_generated.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_platforms_id'), 'content_platforms', ['id'], unique=False)
    op.create_table('content_platform_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_content_id', sa.Integer(), nullable=False),
    sa.Column('variation_label', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('engagement_potential', sa.Float(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('brand_consistency', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_content_id'], ['content_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_platform_variations_id'), 'content_platform_variations', ['id'], unique=False)
    op.create_table('content_platform_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('is_valid', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['content_platform_variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_platform_rules_id'), 'content_platform_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_platform_rules_id'), table_name='content_platform_rules')
    op.drop_table('content_platform_rules')
    op.drop_index(op.f('ix_content_platform_variations_id'), table_name='content_platform_variations')
    op.drop_table('content_platform_variations')
    op.drop_index(op.f('ix_content_platforms_id'), table_name='content_platforms')
    op.drop_table('content_platforms')
    # ### end Alembic commands ###
